server:
  port: 10020
spring:
  application:
    name: angle-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/sys , classpath:/config/user

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka
